apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mobx-barkellato-app
  namespace: other-namespace
spec:
  project: default
  source:
    repoURL: "git@github.com:noaabarki/mobx-barelato.git"
    targetRevision: HEAD
    path: kube/
  destination:
    server: https://kubernetes.default.svc
    namespace: mobx-barkellato-app
  syncPolicy:
    automated: {}
