apiVersion: v1
kind: Namespace
metadata:
  name: "mobx-barkellato-app"
  labels:
    app.kubernetes.io/name: mobx-barkellato
    app.kubernetes.io/instance: mobx-barkellato-abcxzy
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mobx-barkellato-app
    app.kubernetes.io/managed-by: Noaa
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mobx-barkellato
  namespace: "mobx-barkellato-app"
  labels:
    app.kubernetes.io/name: mobx-barkellato
    app.kubernetes.io/instance: mobx-barkellato-abcxzy
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mobx-barkellato-app
    app.kubernetes.io/managed-by: Noaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobx-barkellato
  template:
    metadata:
      labels:
        app: mobx-barkellato
    spec:
      containers:
        - name: mobx-barkellato
          image: noaabarki/mobx-barkellato:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: "service-mobx-barkellato"
  namespace: "mobx-barkellato-app"
  labels:
    app.kubernetes.io/name: mobx-barkellato
    app.kubernetes.io/instance: mobx-barkellato-abcxzy
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mobx-barkellato-app
    app.kubernetes.io/managed-by: Noaa
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: mobx-barkellato
